languageCode = "en-us"
title = "cobrapy - constraint-based metabolic modeling in Python"
baseURL = "https://opencobra.github.io/cobrapy"
relativeURLs = true
preserveTaxonomyNames = true
enableemoji = true

[markup]
  [markup.highlight]
    codeFences = true
    style = "friendly"
    tabWidth = 4

[params]
    mdlversion = "1.3.0"
    mdltheme = "teal-indigo"

[taxonomies]
    tag = "tags"

[caches]
[caches.getjson]
dir = ":resourceDir/_gen"
maxAge = -1
